# Generated by Django 3.0.3 on 2020-02-07 17:30

from django.db import migrations, models
import linkshortcutter.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuttedUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=linkshortcutter.models.code_gen, max_length=5)),
                ('real_url', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('clicks', models.IntegerField()),
            ],
        ),
    ]
