# Generated by Django 3.0.3 on 2020-02-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkshortcutter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuttedurl',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
