# Generated by Django 3.0.3 on 2020-02-08 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkshortcutter', '0002_auto_20200207_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuttedurl',
            options={'ordering': ['clicks']},
        ),
    ]
